### ISSUE TITLE
Translation of Filter of Date Columns

### ISSUE THREAD

**Issue by RogerPenna** [gristlabs/grist-core#852]
I noticed the Date Filter is shown only in English

![image](https://github.com/gristlabs/grist-core/assets/105881500/0de61331-f7a8-4c39-9841-dec73b56b343)

Paul-Grist said the following on the topic in the forum

**Hmm someone needs to go into this code:**
https://github.com/gristlabs/grist-core/blob/d008a32eb3eef6fb7d233b8a0d85fced3209abcd/app/client/ui/DateRangeOptions.ts#L9-L41

**and mark the text there in the special way that makes it translatable. It is a small and hopefully easy piece of work..**

**Comment by thomasweaver627** [comment]
I submitted a PR to fix this! I'm having issues setting up a test environment on my end, but I think my changes should resolve this.

**Comment by fflorent** [comment]
@thomasweaver627 First of all, thank you for your work!

What kind of difficulties do you face?

Here are some resources to help you contribute (in case you missed it, maybe this page is not visible enough):
https://github.com/gristlabs/grist-core/blob/main/.github/CONTRIBUTING.md

You're feedback is welcome! I can make some efforts to clarify things (speaking on my own, I am not a Grist Labs employee)

**Comment by thomasweaver627** [comment]
Thank you @fflorent! I was following the instructions on developer.md but struggling to get it working. I’m assuming it’s just user error, I’m a little new to this :)

I’ll keep playing with it this week and hopefully get it working on my end!
